language: node_js
node_js:
- "0.10"
addons:
  postgresql: 9.3
before_install:
- echo "deb http://ppa.launchpad.net/fkrull/deadsnakes/ubuntu precise main" | sudo tee -a /etc/apt/sources.list
- sudo apt-get update
- sudo apt-get install -y --force-yes --no-install-recommends python3.4 python3.4-dev
- sudo apt-get install -y --force-yes --no-install-recommends postgresql-9.3-postgis-2.1 postgresql-server-dev-9.3 postgresql-contrib-9.3
- sudo apt-get install -y --force-yes --no-install-recommends libgeos-dev libgdal1 libgeos-c1
- sudo apt-get install -y --force-yes --no-install-recommends ruby1.9.1
- sudo apt-get install -y --force-yes --no-install-recommends curl
- mkdir ~/+virtualenv-src
- wget -q -O - https://pypi.python.org/packages/source/v/virtualenv/virtualenv-1.10.1.tar.gz#md5=3a04aa2b32c76c83725ed4d9918e362e | tar -xzf - --strip 1 -C ~/+virtualenv-src
- mkdir -p ~/+env
- export VIRTUAL_ENV=~/+env
- pyvenv-3.4 ~/+env
- source ~/+env/bin/activate
- export GEM_HOME="$VIRTUAL_ENV/gems"
- export GEM_PATH=""
- export PATH=$PATH:"$GEM_HOME/bin"
- echo "CREATE USER angkot PASSWORD 'angkot';" | sudo -u postgres psql
- echo "CREATE DATABASE angkot OWNER angkot ENCODING 'utf8'" | sudo -u postgres psql
- echo "CREATE EXTENSION postgis;" | sudo -u postgres psql angkot
- echo "CREATE EXTENSION postgis_topology;" | sudo -u postgres psql angkot
- echo "CREATE EXTENSION hstore;" | sudo -u postgres psql angkot
- echo "CREATE DATABASE test_angkot OWNER angkot ENCODING 'utf8'" | sudo -u postgres psql
- echo "CREATE EXTENSION postgis;" | sudo -u postgres psql test_angkot
- echo "CREATE EXTENSION postgis_topology;" | sudo -u postgres psql test_angkot
- echo "CREATE EXTENSION hstore;" | sudo -u postgres psql test_angkot
before_script:
- gem install bundle
- ~/+env/bin/pip install -r requirements.txt
- ~/+env/bin/pip install -r dev_requirements.txt
- bundle install
- npm install -g grunt-cli
- npm install
- cp .travis/settings.py angkot/settings/travis.py
- echo 'host all all 127.0.0.1/32 password' | sudo tee -a /etc/postgresql/9.1/main/pg_hba.conf
- sudo service postgresql restart
- grunt
script:
- export PYTHONPATH=`pwd`:$PYTHONPATH
- export DJANGO_SETTINGS_MODULE=angkot.settings.travis
- python manage.py syncdb --noinput
- python manage.py migrate --noinput
- grunt test

